version: '3.8'

services:
  nginx-example:
    container_name: nginx-example
    image: nginx:latest
    networks:
      - network_ngix
  nginx-example2:
    container_name: nginx-example2
    image: nginx:latest
    networks:
      - network_ngix

networks:
  network_ngix:
    name: network_ngix
    driver: bridge