version: '3.8'

services:
  app:
    container_name: app
    build:
      context: "./app"
      dockerfile: Dockerfile
    image: app-golang:1.0.2
    environment:
      - "APP_PORT=8089"
    ports:
      - "8089:8089"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8089/health"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s