version: '3.8'

services:
  app:
    container_name: app
    build:
      context: "./app"
      dockerfile: Dockerfile
    image: "app-golang:1.0.3"
    environment:
      - "APP_PORT=8081"
    ports:
      - "8081:8081"