version: '3.8'

services:
  mongodb-example:
    image: mongo:latest
    container_name: mongodb-example
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: rizal
      MONGO_INITDB_ROOT_PASSWORD: rizal
      MONGO_INITDB_DATABASE: admin
    networks:
      - mongo_network

  mongo-express-example:
    image: mongo-express:latest
    container_name: mongo-express-example
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rizal
      ME_CONFIG_MONGODB_ADMINPASSWORD: rizal
      ME_CONFIG_MONGODB_SERVER: mongodb-example
    depends_on:
      - mongodb-example
    networks:
      - mongo_network
    restart: always

networks:
  mongo_network:
    name: mongo_network
    driver: bridge